version: "3.7"

services:
  bib_bot:
    image: artemgo/bib_bot:0.5
    hostname: bib_bot
    entrypoint: "/app/bib_bot"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
